### ISSUE TITLE
Zero size tag

### ISSUE THREAD

**Issue by efulmo** [mpatric/mp3agic#115]
I have got a MP3 file that is throwing the following error on attempt to process it:

```
Caused by: com.mpatric.mp3agic.InvalidDataException: Zero size tag
	at com.mpatric.mp3agic.AbstractID3v2Tag.unpackHeader(AbstractID3v2Tag.java:157)
	at com.mpatric.mp3agic.AbstractID3v2Tag.unpackTag(AbstractID3v2Tag.java:131)
	at com.mpatric.mp3agic.AbstractID3v2Tag.<init>(AbstractID3v2Tag.java:126)
	at com.mpatric.mp3agic.AbstractID3v2Tag.<init>(AbstractID3v2Tag.java:120)
	at com.mpatric.mp3agic.ID3v24Tag.<init>(ID3v24Tag.java:15)
	at com.mpatric.mp3agic.ID3v2TagFactory.createTag(ID3v2TagFactory.java:11)
	at com.mpatric.mp3agic.Mp3File.initId3v2Tag(Mp3File.java:267)
	at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:83)
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:68)
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:59)
```
The problematic file is attached. When I try to play it in some audio player no errors are shown, so file is not corrupted. Is it a bug in your library? I am using latest 0.9.0 version now. Although the error appeared in 0.8.3 too.
[Deborah Bond - nothing matters (soulpersona raregroove remix).zip](https://github.com/mpatric/mp3agic/files/770957/Deborah.Bond.-.nothing.matters.soulpersona.raregroove.remix.zip)

**Comment by hennr** [comment]
The header seems broken in the given file and mp3agic throws an Exception in that case.
This should be handled differently, e.g. by ignoring the whole header and creating a new on a write operation.

**Comment by simon-gunacker** [comment]
> The header seems broken in the given file and mp3agic throws an Exception in that case.
> This should be handled differently, e.g. by ignoring the whole header and creating a new on a write operation.

It cannot be ignored. The reason is, that tags are read when the file is initialized. So, when reading a file which has not been tagged before, the Exception is thrown before a new tag can be created. 

```
Exception in thread "main" com.mpatric.mp3agic.InvalidDataException: Zero size tag
	at com.mpatric.mp3agic.AbstractID3v2Tag.unpackHeader(AbstractID3v2Tag.java:157)
	at com.mpatric.mp3agic.AbstractID3v2Tag.unpackTag(AbstractID3v2Tag.java:131)
	at com.mpatric.mp3agic.AbstractID3v2Tag.<init>(AbstractID3v2Tag.java:126)
	at com.mpatric.mp3agic.AbstractID3v2Tag.<init>(AbstractID3v2Tag.java:120)
	at com.mpatric.mp3agic.ID3v23Tag.<init>(ID3v23Tag.java:13)
	at com.mpatric.mp3agic.ID3v2TagFactory.createTag(ID3v2TagFactory.java:10)
	at com.mpatric.mp3agic.Mp3File.initId3v2Tag(Mp3File.java:267)
	at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:83)
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:55)
	at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:42)
```
