### ISSUE TITLE
Any example project using mp3agic library in Android Studio?

### ISSUE THREAD

**Issue by JeanSantosReyes** [mpatric/mp3agic#176]
I'm doing a project, where I show a folder of songs in a listview, this list is loaded with an ArrayList; when I try to rename it comes out for example:

  - If the song has meta-data, it allows me to rename a song.
  - But if it doesn't have meta-data, it doesn't allow me to rename a song. [Error image][1]

I managed to rename the song file, working with file.renameTo (newFile), [Rename with File][2], but it doesn't show the change in the listview even though I update the adapter and the arraylist, so I opted to use mp3agic to change the labels, but it shows me the error. [Method code applying mp3agic to rename][3]

I need help. Thanks.

   [1]: https://i.stack.imgur.com/LvR1A.png
   [2]: https://i.stack.imgur.com/YZXoi.png
   [3]: https://i.stack.imgur.com/mLoLQ.png

**Comment by mpatric** [comment]
Can you provide a full stack trace? It would be easier to see what's going on

**Comment by joe-vettek** [comment]
W/System.err: com.mpatric.mp3agic.InvalidDataException: No mpegs frames found
        at com.mpatric.mp3agic.Mp3File.init(Mp3File.java:97)
        at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:58)
        at com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:45)

**Comment by joe-vettek** [comment]
![image](https://user-images.githubusercontent.com/82761814/182178389-4e84244e-bc4f-490a-9351-a908a96ad7df.png)

**Comment by joe-vettek** [comment]
I'm curious about how this offset is verified

**Comment by joe-vettek** [comment]
I may understand that what I opened is actually an m4a file, although it is marked as MP3 file.

**Comment by joe-vettek** [comment]
Here is a supplement. For some mp3 suffix files that are actually m4a files, they may be read successfully and then become unplayable, which is worth noting.
