### ISSUE TITLE
Packing Obselete frames is not supported

### ISSUE THREAD

**Issue by daniksh** [mpatric/mp3agic#84]
When trying to save some mp3 files, an exception shows up in the console:

com.mpatric.mp3agic.NotSupportedException: Packing Obselete frames is not supported
at com.mpatric.mp3agic.ID3v2ObseleteFrame.packFrame(ID3v2ObseleteFrame.java:29)
at com.mpatric.mp3agic.ID3v2Frame.toBytes(ID3v2Frame.java:83)
at com.mpatric.mp3agic.AbstractID3v2Tag.packSpecifiedFrames(AbstractID3v2Tag.java:254)
at com.mpatric.mp3agic.AbstractID3v2Tag.packFrames(AbstractID3v2Tag.java:240)
at com.mpatric.mp3agic.AbstractID3v2Tag.packTag(AbstractID3v2Tag.java:206)
at com.mpatric.mp3agic.AbstractID3v2Tag.toBytes(AbstractID3v2Tag.java:197)
at com.mpatric.mp3agic.Mp3File.save(Mp3File.java:426)`

What does that mean? And how to avoid it?

**Comment by daniksh** [comment]
Fixed this by recreating tag each time. Do not reuse it if you want to support all MP3 tag formats!
`id3v2Tag = new ID3v24Tag();
            mp3.setId3v2Tag(id3v2Tag);`
